# EAP-SIM with a software simulated SIM card
# (based on GSM-Milenage and authentication parameters in
# 3GPP TS 35.208 v6.0.0 4.3.20 Test Set 20)

# Enable control interface for wpa_cli and wpa_gui
ctrl_interface=/var/run/wpa_supplicant
# Use driver to select which BSS to use
ap_scan=2

network={
	ssid="EXAP"
	key_mgmt=WPA-EAP
	proto=WPA2
	pairwise=CCMP
	eap=SIM
	identity="1232010000000000"
	password="90dca4eda45b53cf0f12d7c9c3bc6a89:cb9cccc4b9258e6dca4760379fb82581"
}
