#! /bin/sh

set -e

case "$1" in
  start)
    echo -n "Starting Recovery "
    /usr/bin/recovery
    echo "done"
    ;;
  stop)
    echo -n "No need to stop recovery "
    ;;

*)
    exit 1
;;
esac
exit 0
