##### Interface & driver configuration #####################
interface=eth0
driver=ar6000

##### IEEE 802.11 related configuration ####################
ssid=AR6K
channel_num=6
ignore_broadcast_ssid=0

# Require IEEE 802.1X authorization
ieee8021x=1
own_ip_addr=192.168.2.125
nas_identifier=eap
# RADIUS authentication server
auth_server_addr=192.168.2.116
auth_server_port=1812
auth_server_shared_secret=wifi

acct_server_addr=192.168.2.116
acct_server_port=1812
acct_server_shared_secret=wifi

wpa=2
wpa_key_mgmt=WPA-EAP
wpa_pairwise=CCMP
##### ACL configurations ###################################
# 0 - ignore, ACL will be controlled by wmiconfig
# 1 - Disable ACL
# 2 - Deny
# 3 - Allow
############################################################
#macaddr_acl=0
#deny_mac_file=/opt/deny
#accept_mac_file=/opt/accept
